version: '3'
services:
  mongo:
    image: mongo:3
    ports:
      - "27017:27017"
  
  rabbitmq:
    build: ./rabbitmq
    hostname: "rabbit"
    ports:  
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq/plugins/enabled_plugins:/etc/rabbitmq/enabled_plugins
      
  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "12201:12201/udp"
    volumes:
      - ./logstash-gelf.conf:/etc/logstash/conf.d/gelf.conf